[level]
name        = "test"
creatour    = "Achernar"
description = "A test level."

background = "#1F1F1F"

[[chunk]]
width = 0.375

is_spawnable = true

[[chunk.layer]]
height = 0.125

material = "sand"

[[chunk]]
width = 0.25

is_spawnable = true

[[chunk.layer]]
height = 0.25

material = "dirt"

[[chunk]]
width = 0.375

is_spawnable = false

[[chunk.layer]]
height = 0.375

material = "rock"
