[level]
name        = "test"
creatour    = "Achernar"
description = "A test level."

[[chunk]]
terrain_height = 0.0625

ground = "sand"

[[chunk]]
terrain_height = 0.125

ground = "dirt"

[[chunk]]
terrain_height = 0.25

ground = "stone"
